#!/bin/bash

# --------------------------
# Author : Clément Robert
# written october 2016
# --------------------------
# This program copies a base simulation with all its file-tree 
# except the output files
# Optionally, it can copy specified restart files with -r (-R) flag

# PARSING
#----------------------------------------------------------------------

restartfrom=0

while getopts r:R: option
do
    case $option in
        r|R ) restartfrom=$2 ;
            shift $((OPTIND-1))
            ;;
        *) exit 1;;
    esac
done
            
# gets the absolute path even from relative input
base="/"$(readlink -e $1 | cut --complement -d '/' -f 1,2)
# removes a "/" ending char if provided
target=$(pwd)/$(basename $2)


# SYNCHRONIZATION
#----------------------------------------------------------------------

FLAGS=(
    --exclude="*output/*"  # output files
    --exclude="*.std*"     # .stdout and .stderr generated by mpi
    --exclude="*~"         # temp files
    --exclude="\#*\#"      # emacs autosave files
    )

# main synchronisation
rsync -av "${FLAGS[@]}" $base/ $target 

# optional, addtional synchro including specified restart files
optf="find $base/output  | egrep '[^0-9]$restartfrom.dat'"
autf="find $base/output/ | egrep '/((planet|orbit)[0-9]*|used_rad).dat'"

if [[  $restartfrom > 0 ]]
then
    AUTOINCLUDE=$(eval $autf)
    RESTARTFILES=$(eval $optf)
    rsync -av --include=$RESTARTFILES \
        --include=$AUTOINCLUDE \
        $base/output/*$restartfrom.dat $target/output/
fi


# AUTO-EDITION of files mentioning their own location
#----------------------------------------------------------------------
# /!\ This part may still be subject to bug corrections

sed -i "s!$base!$target!g" $target/jobs/*oar
sed -i "s!$base!$target!g" $target/input*/*par


# SECURITY
#----------------------------------------------------------------------
# we force the user to change persmissions before they can 
# run the simulation in case there is still something wrong

chmod -x $target/*exe 
